### ISSUE TITLE
Object/Substr based index support causes exception

### ISSUE THREAD

**Issue by SridharCR** [pythonutilities/jinjasql#12]
Due to the recent named format changes, in the JinjaSql it maps the keys wrongly, when used inside loops.

**Sample query:**
`
{% for item in payload %}
update schema.tablename set col1 = {{item.col1}} where col2 = {{item.col2}}
{% endfor %}
`

**Error raised:**
`
Exception: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'item'
[SQL: 
    update schema.tablename set col1 = %(item)s.col1 where col2 = %(item)s.col2
]
[parameters: [{'item.col1_1': 'sln', 'item.col2_2': 'ljs'}]
`

**Things to do:**

- [ ] Fix the issue by including the key name 
- [ ] Write a clear test case for different looping scenarios like object access, substr access.
- [ ] Add them in the documentation.

**Comment by SridharCR** [comment]
This type of SQL query is being parsed correctly by jinjasql but the new upgraded variant of sqlalchemy >= 2.x. Kindly rewrite your queries to resolve this issue. 

Work around: The query can be re-written as with the dict based access notation instead of object notation. 
Eg: item["col1"]

Closing this, since it is not an issue per se.

**Comment by PandaWhoCodes** [comment]
@SridharCR can we document this work around and this problem properly in the readme or known issues/ work around page in wiki
