### ISSUE TITLE
Latest release not yet available on pypi

### ISSUE THREAD

**Issue by BigNerd** [pythonutilities/jinjasql#15]
Hi, from https://github.com/sripathikrishnan/jinjasql/issues/50 I learnt you have published v0.1.10 on pypi. Do you have plans to publish all your releases there? Currently, I do not find v0.1.11 on pypi.

**Comment by SridharCR** [comment]
@BigNerd Yeah we're planning to automate the pypi publish workflow. I'll have this issue open for tracking.

**Comment by SridharCR** [comment]
@BigNerd We have pushed the latest version (0.1.11) in the pypi. Will create a new issue to track the pypi workflow automation
