### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by andrewt-cville** [pythonutilities/jinjasql#4]
Thanks for updating and maintaining this library.  Sort of a newbie here - but what's the best way to install this version?  pip/conda still look to the old codebase and version 0.1.8.  Any chance you could update the Install Instructions in the ReadMe with the new info?

**Comment by andrewt-cville** [comment]
Figured out the workaround until it gets added to pip, which was probably obvious, but since this is really just the core.py file, I just copy and pasted to replace what was installed in my local site-packages on the original jinjasql library.  Worked fine.

**Comment by SridharCR** [comment]
Thanks @andrewt-cville. Use this way to install this jinjasql

`pip install git+https://github.com/pythonutilities/jinjasql@main`

I would advice to you use the tagged version. Closing this

**Comment by PandaWhoCodes** [comment]
please use this tag for the latest current release

https://github.com/pythonutilities/jinjasql/tree/0.1.10

More releases here - https://github.com/pythonutilities/jinjasql/releases

**Comment by justinclift** [comment]
@andrewt-cville They've put this onto PyPi as "jinjasql2" just a few minutes ago:

https://pypi.org/project/jinjasql2/

**Comment by andrewt-cville** [comment]
> @andrewt-cville They've added this to PyPi as "jinjasql2" just a few minutes ago:
> 
> 
> 
> https://pypi.org/project/jinjasql2/

Great news. Thank you!
