### ISSUE TITLE
New package name for pypi?

### ISSUE THREAD

**Issue by justinclift** [pythonutilities/jinjasql#8]
With this being a successor to the looks-like-its-dead [jinjasql](https://github.com/sripathikrishnan/jinjasql), would it be possible to get this onto PyPi somehow?

Maybe as "jinjasql2" or something? :smile:

Asking because a project I'm putting time into was considering jinjasql, but we've noticed that it's dead.  If there's a new package name we can just drop into our requirements.txt though, that would make things pretty easy. :smile:

**Comment by PandaWhoCodes** [comment]
currently we are not planning on that.
Refer to this [comment ](https://github.com/pythonutilities/jinjasql/issues/4#issuecomment-1603608799) and add the latest tag/ pinned tag to your requirements.

**Comment by justinclift** [comment]
Thanks for letting us know. :smile:

**Comment by PandaWhoCodes** [comment]
The base code is copyrighted by HashedIn Technologies Pvt. Ltd.
We're looking into the implications of publishing our own since the company is owned by [Deloitte](https://in.linkedin.com/company/hashedin) which is one of the bigger IT firms in the world.

I'll keep this issue open to track our progress.
If you are aware of someone who can help us out in this regard. Do let us know.

**Comment by justinclift** [comment]
Interesting.  Some of that is a bit unclear, so I'll ask a few questions to clarify. :smile:

1. By `the base code` are you meaning the code in the [original jinjasql repository](https://github.com/sripathikrishnan/jinjasql), or are you meaning something to do with [the custom features](https://github.com/pythonutilities/jinjasql/blob/50bf2d568ae7127ce453d5a213d7615841c175db/README.md?plain=1#L1) mentioned in your README?
2. Where you have `the company is owned by Deloitte`, are you meaning the company you and the other people working on this fork are employed by, or something else?

That being said, the original jinjasql's source code is MIT licensed.  It's whole purpose it to allow re-use that's nearly totally unrestricted.  It's nothing like the GPL, which is the "viral" license type thing that gets some places worries.

Oh, if you're employed by Deloitte (as per question 2 above), then they will very, very likely already have some people familiar with Open Source Licensing.  So if you can find them, then you can probably ask those people for pointers.  It shouldn't be *toooooooo* hard to find them (if they exist), it will probably just mean doing a bit of searching on the internal Deloitte intranet or even Google searching for "Deloitte" and "Open Source" then see what turns up.

Does that help? :smile:

**Comment by PandaWhoCodes** [comment]
@SridharCR Can you look into the above comments and see the possibility of publishing pypi.
Lets try and wrap this up by this week if possible.

**Comment by justinclift** [comment]
Any progress with this? :smile:

**Comment by SridharCR** [comment]
@PandaWhoCodes @justinclift Working on this, will update here once it is done.

**Comment by justinclift** [comment]
> ... once it is done.

Thanks.  Any idea how long it might take (even roughly)? :smile:

**Comment by SridharCR** [comment]
Apologies for the delay, but I'm excited to share some great news with you! We have just released the "jinjasql2" package to PyPI.🚀
`pip install jinjasql2`

**Comment by justinclift** [comment]
Awesome!  Thanks heaps @SridharCR. :grin:

**Comment by justinclift** [comment]
Oh, I guess we can close this issue now. :smile:

**Comment by justinclift** [comment]
Probably needs the README updated with the new name too, so people know to use it (etc). :smile:

**Comment by SridharCR** [comment]
@justinclift yeah we have updated the docs as well. 😄
